name: Terraform deploy workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}/terraform
    steps:
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: TF_WORKSPACE=us-${{ inputs.env }}-${{ inputs.project }} terraform init

      - name: Terraform apply
        run: TF_WORKSPACE=us-${{ inputs.env }}-${{ inputs.project }} terraform apply -auto-approve -var="environment=${{ inputs.env }}" -var="project=${{ inputs.project }}"
