name: Node.js tests

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: true
        type: 'string'
      node-version:
        description: 'Node version'
        required: true
        type: 'string'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies  
        run: npm install

      - name: Run tests
        run: npm test