name: Python tests

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: true
        type: 'string'
      python-version:
        description: 'Python version'
        required: true
        type: 'string'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check architecture
        run: echo "is_aarch64=$(if [ $(uname -m) = 'aarch64' ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

      - name: Set up Python
        if: env.is_aarch64 != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up ARM Python
        if: env.is_aarch64 == 'true'
        uses: deadsnakes/action@v2.1.1
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - name: Run tests
        run: python -m unittest discover -v -s ./tests/ -p "*_test.py"
