name: Terraform deploy workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      env:
        required: true
        type: string
      project-type:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}/terraform
    env:
      TF_WORKSPACE: us-${{ inputs.env }}-${{ inputs.project }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package Python source code
        if: inputs.project-type == 'python'
        working-directory: ${{ inputs.project }}
        run: |
          pip install -r requirements.txt
          cd src && zip -r ../terraform/deployment-package.zip .
      
      - name: Package Node.js source code
        if: inputs.project-type == 'nodejs'
        working-directory: ${{ inputs.project }}
        run: |
          npm i
          cd src && zip -r ../terraform/deployment-package.zip .

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Copy modules code
        run: cp -R ../../terraform-modules/ modules/

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve -var="environment=${{ inputs.env }}" -var="project=${{ inputs.project }}"
