name: dynamodb-stream-lambda CI/CD

on:
  push:
    branches:
      - "*"
    paths:
      - "dynamodb-stream-lambda/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "dynamodb-stream-lambda/**"
  release:
    types: [published]

jobs:
  node:
    name: Node
    uses: ./.github/workflows/workflow-nodejs.yml
    with:
      project: dynamodb-stream-lambda
      node-version: 20.x
    secrets: inherit
