name: dynamodb-stream-lambda plan to dev

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'dynamodb-stream-lambda/**'

jobs:
  plan-dynamodb-stream-lambda-dev:
    uses: ./.github/workflows/.terraform-plan.yml
    with:
      project: dynamodb-stream-lambda
      env: dev
      project-type: nodejs
    secrets: inherit