name: Generate Preview Lambda CI/CD

env:
  PROJECT: generate-preview-lambda
  NODE_VERSION: '20.x'
  PACK_DEPENDENCIES: false

on:
  push:
    branches:
      - "main"
    paths:
      - "${{ env.PROJECT }}/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "${{ env.PROJECT }}/**"
  release:
    types: [published]

jobs:
  ci-cd:
    uses: ./.github/workflows/workflow-nodejs.yml
    with:
      working-directory: ${{ env.PROJECT }}
      node-version: ${{ env.NODE_VERSION }}
      pack-dependencies: ${{ env.PACK_DEPENDENCIES }}
      tf-workspace-dev: us-dev-${{ env.PROJECT }}
      tf-workspace-prod: us-prd-${{ env.PROJECT }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
