name: Generate Preview Lambda CI/CD

on:
  push:
  #   branches:
  #     - "main"
  #   paths:
  #     - "${{ env.PROJECT }}/**"
  # pull_request:
  #   branches:
  #     - "*"
  #   paths:
  #     - "${{ env.PROJECT }}/**"
  # release:
  #   types: [published]

jobs:
  ci-cd:
    uses: ./.github/workflows/workflow-nodejs.yml
    with:
      working-directory: generate-preview-lambda
      node-version: 20.x
      pack-dependencies: false
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
