name: generate-preview-lambda CI/CD

on:
  push:
    branches:
      - "*"
    paths:
      - "generate-preview-lambda/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "generate-preview-lambda/**"
  release:
    types: [published]

jobs:
  node:
    name: Node
    uses: ./.github/workflows/workflow-nodejs.yml
    with:
      project: generate-preview-lambda
      node-version: 20.x
      pack-dependencies: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
