name: get-url-lambda tests

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'get-url-lambda/**'
  push:
    branches:
      - '*'
    paths:
      - 'get-url-lambda/**'

jobs:
  get-url-lambda-tests:
    uses: ./.github/workflows/.python-tests.yml
    with:
      working-directory: get-url-lambda
      python-version: 3.12
