name: get-preview-url-lambda

on:
  push:
    branches:
      - "*"
    paths:
      - "src/get-preview-url-lambda/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "src/get-preview-url-lambda/**"
  release:
    types: [published]

jobs:
  node:
    name: Node
    uses: ./.github/workflows/workflow-nodejs.yml
    with:
      project: get-preview-url-lambda
      node-version: 20.x
    secrets: inherit
