name: CI/CD Pipeline

on:
  push:
  pull_request:

env:
  NODE_VERSION: 20.x
  PYTHON_VERSION: 3.12

jobs:
  javascript-tests:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:unit

  python-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [get-url-lambda]
    defaults:
      run:
        working-directory: src/${{ matrix.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check architecture
        id: check_arch
        run: echo "::set-output name=is_aarch64::$(if [ $(uname -m) = 'aarch64' ]; then echo 'true'; else echo 'false'; fi)"

      - name: Setup Python (x86_64)
        if: steps.check_arch.outputs.is_aarch64 == 'false'
        uses: actions/setup-python@v5
        with:
          python-version: $PYTHON_VERSION

      - name: Setup Python (ARM)
        if: steps.check_arch.outputs.is_aarch64 == 'true'
        uses: deadsnakes/action@v3.2.0
        with:
          python-version: $PYTHON_VERSION

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m unittest discover -v -s ./ -p "*_test.py"

  terraform-plan-dev:
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      working-directory: terraform/shared-infrastructure
      environment: dev
      action: plan
    secrets: inherit

  terraform-plan-prd:
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      working-directory: terraform/shared-infrastructure
      environment: prd
      action: plan
    secrets: inherit

  package-source-code:
    needs: [
      javascript-tests,
      python-tests,
      terraform-plan-dev,
      terraform-plan-prd
    ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [dynamodb-stream-lambda, generate-preview-lambda, websocket-authorizer-lambda]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ./deploy.sh ${{ matrix.project }} local

  terraform-apply-dev:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    needs: package-source-code
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      working-directory: terraform/shared-infrastructure
      environment: dev
      action: apply
    secrets: inherit

  dev-system-test:
    needs: terraform-apply-dev
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    name: System tests (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: system-tests
    env:
      environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  terraform-apply-prd:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    needs: dev-system-test
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      working-directory: terraform/shared-infrastructure
      environment: prd
      action: apply
    secrets: inherit

  prd-system-test:
    needs: terraform-apply-prd
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'
    name: System tests (prd)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: system-tests
    env:
      environment: prd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
