name: Shared infrastructure provisioning

on:
  push:
    branches:
      - '**'
    paths:
      - 'shared-infrastructure/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'shared-infrastructure/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shared-infrastructure/terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
      
      - name: Terraform plan
        run: terraform plan -var="environment=dev"

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="environment=dev"
