name: Shared infrastructure provisioning

on:
  push:
    branches:
      - '**'
    paths:
      - 'shared-infrastructure/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'shared-infrastructure/**'
  workflow_dispatch:

jobs:
  plan_dev:
    uses: ./.github/workflows/terraform-plan-workflow.yml
    with:
      project: shared-infrastructure
      env: dev
    secrets: inherit

  deploy_dev:
    needs: [plan_dev]
    uses: ./.github/workflows/terraform-deploy-workflow.yml
    with:
      project: shared-infrastructure
      env: dev
    secrets: inherit

  plan_prd:
    needs: [deploy_dev]
    uses: ./.github/workflows/terraform-plan-workflow.yml
    with:
      project: shared-infrastructure
      env: dev
    secrets: inherit

  deploy_prd:
    needs: [plan_prd]
    uses: ./.github/workflows/terraform-deploy-workflow.yml
    with:
      project: shared-infrastructure
      env: dev
    secrets: inherit
  
