name: shared-infrastructure deploy to prd

on:
  push:
    branches:
      - 'prod'
    paths:
      - 'shared-infrastructure/**'

jobs:
  deploy-shared-infrastructure-prd:
    uses: ./.github/workflows/.terraform-deploy.yml
    with:
      project: shared-infrastructure
      env: prd
    secrets: inherit
