name: CI/CD for Shorten URL Lambda

on:
  push:
    branches:
      - '**'
    paths:
      - 'shorten-url-lambda/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'shorten-url-lambda/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Copy shared terraform scripts
        run: cp -R terraform/shared/* shorten-url-lambda/terraform

      - name: Terraform init
        working-directory: shorten-url-lambda/terraform
        run: terraform init

      - name: Terraform validate
        working-directory: shorten-url-lambda/terraform
        run: terraform validate
      
      - name: Terraform plan
        working-directory: shorten-url-lambda/terraform
        run: terraform plan

      - name: Package Lambda function
        working-directory: shorten-url-lambda/src
        run: zip -r ../terraform/deployment-package.zip .

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        working-directory: shorten-url-lambda/terraform
        run: terraform apply
