name: shorten-url-lambda plan to dev

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'shorten-url-lambda/**'

jobs:
  plan-shorten-url-lambda-dev:
    uses: ./.github/workflows/.terraform-plan.yml
    with:
      project: shorten-url-lambda
      env: dev
      project-type: nodejs
    secrets: inherit