name: shorten-url-lambda deploy to prd

on:
  push:
    branches:
      - 'prod'
    paths:
      - 'shorten-url-lambda/**'

jobs:
  deploy-shorten-url-lambda-prd:
    uses: ./.github/workflows/.terraform-deploy.yml
    with:
      project: shorten-url-lambda
      env: prd
    secrets: inherit