name: shorten-url-lambda tests

on:
  push:
    branches:
      - '*'
    paths:
      - 'shorten-url-lambda/**'

jobs:
  test-shorten-url-lambda:
    uses: ./.github/reusable-workflows/nodejs-tests.yml
    with:
      working-directory: shorten-url-lambda
      node-version: 20.x
