name: shorten-url-lambda pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - 'shorten-url-lambda/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'shorten-url-lambda/**'
  workflow_dispatch:

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shorten-url-lambda/src
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test
  
  plan_dev:
    uses: ./.github/workflows/terraform-plan-workflow.yml
    with:
      project: shorten-url-lambda
      env: dev
    secrets: inherit

  deploy_dev:
    needs: [plan_dev]
    uses: ./.github/workflows/terraform-deploy-workflow.yml
    with:
      project: shorten-url-lambda
      env: dev
    secrets: inherit
  
  plan_prd:
    needs: [deploy_dev]
    uses: ./.github/workflows/terraform-plan-workflow.yml
    with:
      project: shorten-url-lambda
      env: prd
    secrets: inherit

  deploy_prd:
    needs: [plan_prd]
    uses: ./.github/workflows/terraform-deploy-workflow.yml
    with:
      project: shorten-url-lambda
      env: prd
    secrets: inherit
