name: System tests

on:
  push:
    branches:
      - 'main'

jobs:
  system-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: system-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Delay the tests before all the changes are applied # This is not so smart, but it works for now
        run: sleep 180s

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies for system tests
        run: npm install

      - name: Run system tests
        run: npm test
