name: Terraform deploy workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}/terraform
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rutkowski-tomasz

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: TF_WORKSPACE=us-${{ inputs.env }}-${{ inputs.project }} terraform init

      - name: Package Lambda function
        working-directory: ${{ inputs.project }}/src
        run: zip -r ../terraform/deployment-package.zip .

      - name: Terraform apply
        run: TF_WORKSPACE=us-${{ inputs.env }}-${{ inputs.project }} terraform apply -auto-approve -var="environment=${{ inputs.env }}"
