on:
  workflow_call:
    inputs:
      project:
        description: 'Project name/working-directory'
        required: true
        type: string
      node-version:
        description: 'Node version'
        required: true
        type: string
      pack-dependencies:
        description: 'Flag whether to install node_modules inside deployment package'
        required: true
        type: boolean

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  dev:
    needs: [test]
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      project: ${{ inputs.project }}
      environment: dev
      action: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && 'apply' || 'plan' }}
      pack-dependencies: ${{ inputs.pack-dependencies }}
    secrets: inherit

  prd:
    needs: [dev]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      project: ${{ inputs.project }}
      environment: prd
      action: apply
      pack-dependencies: ${{ inputs.pack-dependencies }}
    secrets: inherit
