name: "- Terraform Workflow"

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
        description: 'Action to perform: plan or apply'

jobs:
  terraform:
    name: Terraform ${{ inputs.action }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.action == 'apply' && inputs.environment || '' }}
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform init
        run: terraform init

      - name: Terraform select '${{ inputs.environment }}' workspace
        run: terraform workspace select ${{ inputs.environment }}

      - name: Terraform plan
        if: inputs.action == 'plan'
        run: terraform plan

      - name: Terraform apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve
