name: "- Python workflow"

on:
  workflow_call:
    inputs:
      project:
        description: 'Project name/working-directory'
        required: true
        type: string
      python-version:
        description: 'Python version'
        required: true
        type: string

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check architecture
        run: echo "is_aarch64=$(if [ $(uname -m) = 'aarch64' ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV

      - name: Setup Python (x86_64)
        if: env.is_aarch64 != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
  
      - name: Setup Python (ARM)
        if: env.is_aarch64 == 'true'
        uses: deadsnakes/action@v2.1.1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -v -s ./tests/ -p "*_test.py"

  dev:
    needs: [test]
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      project: ${{ inputs.project }}
      environment: dev
      action: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && 'apply' || 'plan' }}
    secrets: inherit

  prd:
    needs: [dev]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      project: ${{ inputs.project }}
      environment: prd
      action: apply
    secrets: inherit
